baseURL = "http://localhost:1313/"
title = "Nocco Example Site"
theme = "nocco"

[taxonomies]
category = "categories"

[params]
theme_seconds = "1"
description = "A minimal example site for the Nocco theme."
header_quote = "Trust the Process."
footer_quote = "Less, but better."
author_username = "example"
bluesky_username = "example.bsky.social"
email = "hello@example.com"

[[menus.main]]
name = "About"
url = "/about/"
weight = 1

[[menus.main]]
name = "Archive"
url = "/post/"
weight = 2

[[menus.main]]
name = "Photos"
url = "/photos/"
weight = 3
