baseURL = "http://localhost:1313/"
title = "Nocco Example Site"
theme = "nocco"

[params]
theme_seconds = "1"
description = "A minimal example site for the Nocco theme."
header_quote = "Trust the Process."
footer_quote = "Less, but better."

[params.author]
username = "example"

[params.social]
mastodon = "https://mastodon.social/@username"
bluesky = "https://bsky.app/profile/username"
email = "hello@example.com"

[[menus.main]]
name = "About"
url = "/about/"
weight = 1

[[menus.main]]
name = "Archive"
url = "/post/"
weight = 2
